version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: funnels-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - funnels-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: funnels-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - funnels-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: funnels-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - funnels-network

  nginx:
    image: nginx:alpine
    container_name: funnels-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - funnels-network

networks:
  funnels-network:
    driver: bridge

volumes:
  dbdata:
